"""
models.py — SQLAlchemy 2.x async ORM models and database helpers.

Exports
-------
Base                 Declarative base class.
AudioGeneration      ORM model representing one TTS job / audio file.
async_engine         Async SQLAlchemy engine (singleton, created once).
AsyncSessionLocal    Async session factory; use as an async context manager.
init_db()            Creates tables on first startup (idempotent).
get_session()        FastAPI dependency that yields an AsyncSession.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncGenerator
from datetime import datetime, timezone

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.config import settings


# ---------------------------------------------------------------------------
# Engine + session factory
# ---------------------------------------------------------------------------

async_engine = create_async_engine(
    settings.DATABASE_URL,
    echo=False,          # set to True only for debugging — very noisy
    pool_pre_ping=True,  # detect stale connections before handing them out
    pool_size=5,
    max_overflow=10,
)

AsyncSessionLocal: async_sessionmaker[AsyncSession] = async_sessionmaker(
    bind=async_engine,
    expire_on_commit=False,  # keep attributes accessible after commit
    class_=AsyncSession,
)


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""


# ---------------------------------------------------------------------------
# ORM Models
# ---------------------------------------------------------------------------

class AudioGeneration(Base):
    """
    Represents a single TTS generation job.

    Columns
    -------
    id          UUID primary key, generated by the application layer so it can
                be returned to the caller immediately in the HTTP response.
    input_text  The raw text submitted for synthesis (no length limit).
    model_name  Symbolic name of the TTS backend: "fish_speech" | "xtts".
    file_path   Absolute path to the generated .wav file on disk.
                NULL while the job has not yet completed successfully.
    status      One of: "pending" | "processing" | "done" | "error".
    created_at  Set by the DB server at INSERT time (UTC).
    """

    __tablename__ = "audio_generations"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    input_text: Mapped[str] = mapped_column(Text, nullable=False)
    model_name: Mapped[str] = mapped_column(String(64), nullable=False)
    voice_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    file_path: Mapped[str | None] = mapped_column(String(512), nullable=True)
    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="pending",
        server_default="pending",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
    )

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        """Return a JSON-serialisable representation of this record."""
        return {
            "id": str(self.id),
            "input_text": self.input_text,
            "model_name": self.model_name,
            "voice_id": self.voice_id,
            "file_path": self.file_path,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return (
            f"<AudioGeneration id={self.id!s} model={self.model_name!r}"
            f" status={self.status!r}>"
        )


# ---------------------------------------------------------------------------
# Database lifecycle helpers
# ---------------------------------------------------------------------------

async def init_db() -> None:
    """
    Create all tables that do not yet exist.

    Safe to call multiple times (uses CREATE TABLE IF NOT EXISTS semantics via
    checkfirst=True). Should be called once inside the FastAPI lifespan.
    """
    async with async_engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all, checkfirst=True)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency that provides a database session per request.

    Usage
    -----
    ::

        @router.get("/example")
        async def example(session: AsyncSession = Depends(get_session)):
            ...
    """
    async with AsyncSessionLocal() as session:
        yield session
